version: '3.8'

services:
  # Banco de Dados MongoDB para a aplicação ODM
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Barramento de Eventos Redis
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Interface Gráfica para o Redis
  redis-ui:
    image: redislabs/redisinsight:latest
    container_name: redis-ui
    ports:
      - "8001:8001"
    volumes:
      - redisinsight_data:/db

volumes:
  mongodb_data:
  redis_data:
  redisinsight_data:
