version: "3.8"

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: api_biblioteca
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_HOST=localhost
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=biblioteca
    depends_on:
      - mongodb

volumes:
  mongodb_data: